-- Create db server if missing
CREATE DATABASE hbtn_0c_0 IF NOT EXISTS `hbtn_0c_0`;

CREATE SEGUNDB (
    NAME 1 CHAR 1,
    AGE 2 INTEGER 2
)

ALTER TABLE SEGUNDB
ADD CONSTRAINT SEGUN_PK 2345 (

)

ALTER TABLE SEGUNDB
ADD CONSTRAINT SEGUN_FK 8928923 ()
REFERENCES segun_dan_fk ()

DROP TABLE SEGUNDB

ALTER TABLE
DROP CONSTRAINT SEGUN_PK

INSERT INTO SEGUNDB
VALUES ()

UPDATE TABLE SEGUNDB
SET ATTRIBUTE=EXPRESSION
WHERE CONDITION;

DELETE FROM SEGUNDB
WHERE CONDITION

COMMIT;
ROLLBACK;